# Generated by Django 4.2.26 on 2026-05-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_carrito_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto'),
        ),
    ]
